---
- hosts: all

  vars:
    locale: en_US.UTF-8 # or en_US.utf8
    timezone: Asia/Manila

  handlers:
  - name: update tzdata
    command: /usr/sbin/dpkg-reconfigure --frontend noninteractive tzdata
    become: yes

  tasks:
  - apt: pkg=linux-image-extra-{{ ansible_kernel }} state=present update_cache=yes cache_valid_time=3600
    become: yes

  - name: Make sure NTP is installed
    apt: pkg=ntp state=latest
    become: yes

  - name: Upgrade docker-engine
    apt: pkg=docker-engine state=latest
    become: yes

  - name: set locale to {{locale}}
    command: /usr/sbin/update-locale LANG={{locale}} LC_ALL={{locale}}
    become: yes
    when: ansible_env.LANG != "{{locale}}"

  - name: Check /etc/timezone
    command: cat /etc/timezone
    register: cat_etc_timezone
    changed_when: false

  - name: Set timezone
    command: timedatectl set-timezone {{timezone}}
    become: yes
    when: cat_etc_timezone.stdout != "{{timezone}}"
